# Generated by Django 4.1.7 on 2023-04-15 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import infoAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expierd_at', models.DateTimeField(default=infoAPI.models.in_three_days)),
                ('edits_time', models.IntegerField(default=1)),
                ('view', models.IntegerField(default=0)),
                ('liked', models.IntegerField(default=0)),
                ('shared', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='postInfo',
            fields=[
                ('Date', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(default='default/1.png', upload_to='photo/%y/%m/%d')),
                ('phone_number', models.IntegerField(default=12345678)),
                ('PostDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infoAPI.postdetail')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoAPI.location')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
